// =============================================================
// Chimboy — static mock data
// All data is plain JS. Services in this folder return it via
// async functions so they can later be swapped for real APIs.
// =============================================================

// Placeholder image generator (red brand theme). Replace with real CDN assets later.
const img = (label, color = 'D32F2F') =>
  `https://placehold.co/600x600/${color}/FFFFFF/png?text=${encodeURIComponent(label)}&font=poppins`;

const banner = (label, color = 'B71C1C') =>
  `https://placehold.co/1600x600/${color}/FFFFFF/png?text=${encodeURIComponent(label)}&font=poppins`;

export const categories = [
  { id: 1, name_uz: 'Mayonezlar', name_ru: 'Майонезы', slug: 'mayonnaises', icon: 'Egg', image: img('Mayonez') },
  { id: 2, name_uz: 'Ketchuplar', name_ru: 'Кетчупы', slug: 'ketchups', icon: 'Soup', image: img('Ketchup', 'C62828') },
  { id: 3, name_uz: 'Souslar', name_ru: 'Соусы', slug: 'sauces', icon: 'Droplet', image: img('Sous', 'B71C1C') },
  { id: 4, name_uz: 'Gorchitsa', name_ru: 'Горчица', slug: 'mustard', icon: 'Flame', image: img('Gorchitsa', 'F57F17') },
  { id: 5, name_uz: 'Adjika', name_ru: 'Аджика', slug: 'adjika', icon: 'Pepper', image: img('Adjika', 'C62828') },
  { id: 6, name_uz: "Sovg'a to'plamlari", name_ru: 'Подарочные наборы', slug: 'gift-sets', icon: 'Gift', image: img('Sovga', 'FF6F00') },
];

// Helper to build 3 images per product
const gallery = (label, color) => [img(label, color), img(`${label} 2`, color), img(`${label} 3`, color)];

export const products = [
  {
    id: 1,
    name_uz: 'Provansal Mayonez 67%',
    name_ru: 'Майонез Провансаль 67%',
    slug: 'provansal-mayonez-67',
    category: 'mayonnaises',
    description_uz: "Klassik Provansal mayonezi — yuqori yog'lilikdagi, nozik va boy ta'mga ega. Salatlar va taomlar uchun ideal.",
    description_ru: 'Классический майонез Провансаль — с высокой жирностью, нежным и насыщенным вкусом. Идеален для салатов и блюд.',
    ingredients_uz: "O'simlik yog'i, suv, tuxum sarig'i, sirka, tuz, shakar, xantal kukuni",
    ingredients_ru: 'Растительное масло, вода, яичный желток, уксус, соль, сахар, горчичный порошок',
    images: gallery('Provansal'),
    price: 28000,
    oldPrice: 35000,
    discount: 20,
    weight: 400,
    unit: 'g',
    rating: 4.8,
    reviewCount: 124,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "0°C dan +14°C gacha haroratda saqlang. Ochilgandan keyin sovutgichda 30 kun.",
    storageInfo_ru: 'Хранить при температуре от 0°C до +14°C. После вскрытия 30 дней в холодильнике.',
  },
  {
    id: 2,
    name_uz: "Yengil Mayonez 30%",
    name_ru: 'Майонез Лёгкий 30%',
    slug: 'yengil-mayonez-30',
    category: 'mayonnaises',
    description_uz: "Kam yog'li yengil mayonez — sog'lom turmush tarzini sevuvchilar uchun. Kaloriyasi past.",
    description_ru: 'Лёгкий майонез с пониженной жирностью — для тех, кто следит за здоровьем. Низкокалорийный.',
    ingredients_uz: "Suv, o'simlik yog'i, tuxum sarig'i, sirka, tuz, shakar, limon kislotasi",
    ingredients_ru: 'Вода, растительное масло, яичный желток, уксус, соль, сахар, лимонная кислота',
    images: gallery('Yengil', 'E53935'),
    price: 22000,
    oldPrice: null,
    discount: null,
    weight: 400,
    unit: 'g',
    rating: 4.5,
    reviewCount: 87,
    isNew: true,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "0°C dan +14°C gacha haroratda saqlang.",
    storageInfo_ru: 'Хранить при температуре от 0°C до +14°C.',
  },
  {
    id: 3,
    name_uz: "Sarimsoqli Mayonez",
    name_ru: 'Майонез с чесноком',
    slug: 'sarimsoqli-mayonez',
    category: 'mayonnaises',
    description_uz: "Tabiiy sarimsoq qo'shilgan mayonez — kabob va go'shtli taomlar uchun mukammal hamroh.",
    description_ru: 'Майонез с натуральным чесноком — отличное дополнение к шашлыку и мясным блюдам.',
    ingredients_uz: "O'simlik yog'i, suv, tuxum sarig'i, sarimsoq, sirka, tuz, ziravorlar",
    ingredients_ru: 'Растительное масло, вода, яичный желток, чеснок, уксус, соль, специи',
    images: gallery('Sarimsoq', 'C62828'),
    price: 31000,
    oldPrice: 38000,
    discount: 18,
    weight: 400,
    unit: 'g',
    rating: 4.9,
    reviewCount: 156,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "0°C dan +14°C gacha. Ochilgandan keyin 25 kun.",
    storageInfo_ru: 'От 0°C до +14°C. После вскрытия 25 дней.',
  },
  {
    id: 4,
    name_uz: "Premium Mayonez 72%",
    name_ru: 'Майонез Премиум 72%',
    slug: 'premium-mayonez-72',
    category: 'mayonnaises',
    description_uz: "Eng yuqori yog'lilikdagi premium mayonez. Bayram dasturxonlari uchun maxsus retsept.",
    description_ru: 'Премиальный майонез высшей жирности. Особый рецепт для праздничного стола.',
    ingredients_uz: "O'simlik yog'i, tuxum sarig'i, suv, sirka, tuz, shakar, xantal",
    ingredients_ru: 'Растительное масло, яичный желток, вода, уксус, соль, сахар, горчица',
    images: gallery('Premium', 'B71C1C'),
    price: 39000,
    oldPrice: null,
    discount: null,
    weight: 900,
    unit: 'g',
    rating: 4.7,
    reviewCount: 98,
    isNew: false,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "0°C dan +14°C gacha haroratda saqlang.",
    storageInfo_ru: 'Хранить при температуре от 0°C до +14°C.',
  },
  {
    id: 5,
    name_uz: "Klassik Ketchup",
    name_ru: 'Кетчуп Классический',
    slug: 'klassik-ketchup',
    category: 'ketchups',
    description_uz: "Yetuk pomidordan tayyorlangan klassik ketchup. Tabiiy, quyuq va boy ta'm.",
    description_ru: 'Классический кетчуп из спелых томатов. Натуральный, густой и насыщенный вкус.',
    ingredients_uz: "Pomidor pastasi, suv, shakar, tuz, sirka, ziravorlar",
    ingredients_ru: 'Томатная паста, вода, сахар, соль, уксус, специи',
    images: gallery('Ketchup', 'C62828'),
    price: 18000,
    oldPrice: 24000,
    discount: 25,
    weight: 350,
    unit: 'g',
    rating: 4.6,
    reviewCount: 142,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang. Ochilgandan keyin sovutgichda.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте. После вскрытия в холодильнике.',
  },
  {
    id: 6,
    name_uz: "Achchiq Ketchup",
    name_ru: 'Кетчуп Острый',
    slug: 'achchiq-ketchup',
    category: 'ketchups',
    description_uz: "Qalampir qo'shilgan achchiq ketchup. Achchiq ta'mni sevuvchilar uchun.",
    description_ru: 'Острый кетчуп с добавлением перца. Для любителей острого вкуса.',
    ingredients_uz: "Pomidor pastasi, suv, qizil qalampir, shakar, tuz, sirka, ziravorlar",
    ingredients_ru: 'Томатная паста, вода, красный перец, сахар, соль, уксус, специи',
    images: gallery('Achchiq', 'B71C1C'),
    price: 19000,
    oldPrice: null,
    discount: null,
    weight: 350,
    unit: 'g',
    rating: 4.7,
    reviewCount: 113,
    isNew: true,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте.',
  },
  {
    id: 7,
    name_uz: "Shashlik Ketchup",
    name_ru: 'Кетчуп для шашлыка',
    slug: 'shashlik-ketchup',
    category: 'ketchups',
    description_uz: "Kabob uchun maxsus ketchup — tutun ta'mi va ziravorlar bilan boyitilgan.",
    description_ru: 'Особый кетчуп для шашлыка — с дымным вкусом и специями.',
    ingredients_uz: "Pomidor pastasi, suv, ziravorlar, shakar, tuz, sirka, tutun aromasi",
    ingredients_ru: 'Томатная паста, вода, специи, сахар, соль, уксус, аромат дыма',
    images: gallery('Shashlik', 'C62828'),
    price: 21000,
    oldPrice: 26000,
    discount: 19,
    weight: 500,
    unit: 'g',
    rating: 4.8,
    reviewCount: 167,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте.',
  },
  {
    id: 8,
    name_uz: "Pishloqli Sous",
    name_ru: 'Сырный соус',
    slug: 'pishloqli-sous',
    category: 'sauces',
    description_uz: "Krem-pishloq asosidagi nozik sous. Fri kartoshka va naggetslar uchun ideal.",
    description_ru: 'Нежный соус на основе сливочного сыра. Идеален для картофеля фри и наггетсов.',
    ingredients_uz: "Suv, pishloq, o'simlik yog'i, tuxum sarig'i, tuz, ziravorlar",
    ingredients_ru: 'Вода, сыр, растительное масло, яичный желток, соль, специи',
    images: gallery('Pishloq', 'F57F17'),
    price: 26000,
    oldPrice: null,
    discount: null,
    weight: 200,
    unit: 'g',
    rating: 4.6,
    reviewCount: 76,
    isNew: true,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang. Ochilgandan keyin 14 kun.",
    storageInfo_ru: 'Хранить в холодильнике. После вскрытия 14 дней.',
  },
  {
    id: 9,
    name_uz: "Sezar Sousi",
    name_ru: 'Соус Цезарь',
    slug: 'sezar-sousi',
    category: 'sauces',
    description_uz: "Mashhur Sezar salati uchun mo'ljallangan an'anaviy sous.",
    description_ru: 'Традиционный соус для знаменитого салата Цезарь.',
    ingredients_uz: "O'simlik yog'i, suv, tuxum sarig'i, parmezan, ankovus, sarimsoq, ziravorlar",
    ingredients_ru: 'Растительное масло, вода, яичный желток, пармезан, анчоусы, чеснок, специи',
    images: gallery('Sezar', 'D32F2F'),
    price: 29000,
    oldPrice: 34000,
    discount: 15,
    weight: 200,
    unit: 'g',
    rating: 4.5,
    reviewCount: 64,
    isNew: false,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
  {
    id: 10,
    name_uz: "Tartar Sousi",
    name_ru: 'Соус Тартар',
    slug: 'tartar-sousi',
    category: 'sauces',
    description_uz: "Baliq va dengiz mahsulotlari uchun klassik tartar sousi, bodring va ko'katlar bilan.",
    description_ru: 'Классический соус тартар для рыбы и морепродуктов, с огурцами и зеленью.',
    ingredients_uz: "Mayonez asosi, tuzlangan bodring, ko'katlar, sarimsoq, limon",
    ingredients_ru: 'Майонезная основа, солёные огурцы, зелень, чеснок, лимон',
    images: gallery('Tartar', 'E53935'),
    price: 25000,
    oldPrice: null,
    discount: null,
    weight: 200,
    unit: 'g',
    rating: 4.4,
    reviewCount: 52,
    isNew: false,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
  {
    id: 11,
    name_uz: "BBQ Sousi",
    name_ru: 'Соус BBQ',
    slug: 'bbq-sousi',
    category: 'sauces',
    description_uz: "Amerikacha barbekyu sousi — shirin va achchiq, tutun ta'mi bilan.",
    description_ru: 'Американский соус барбекю — сладко-острый, с дымным вкусом.',
    ingredients_uz: "Pomidor pastasi, shakar, sirka, ziravorlar, tutun aromasi, tuz",
    ingredients_ru: 'Томатная паста, сахар, уксус, специи, аромат дыма, соль',
    images: gallery('BBQ', 'B71C1C'),
    price: 27000,
    oldPrice: 32000,
    discount: 16,
    weight: 300,
    unit: 'g',
    rating: 4.7,
    reviewCount: 91,
    isNew: true,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Salqin joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном месте.',
  },
  {
    id: 12,
    name_uz: "Klassik Gorchitsa",
    name_ru: 'Горчица классическая',
    slug: 'klassik-gorchitsa',
    category: 'mustard',
    description_uz: "An'anaviy o'tkir gorchitsa. Go'sht taomlari va sosiskalar uchun.",
    description_ru: 'Традиционная острая горчица. Для мясных блюд и сосисок.',
    ingredients_uz: "Xantal urug'i, suv, sirka, tuz, shakar, ziravorlar",
    ingredients_ru: 'Горчичные зёрна, вода, уксус, соль, сахар, специи',
    images: gallery('Gorchitsa', 'F57F17'),
    price: 14000,
    oldPrice: null,
    discount: null,
    weight: 200,
    unit: 'g',
    rating: 4.5,
    reviewCount: 73,
    isNew: false,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте.',
  },
  {
    id: 13,
    name_uz: "Dijon Gorchitsasi",
    name_ru: 'Дижонская горчица',
    slug: 'dijon-gorchitsasi',
    category: 'mustard',
    description_uz: "Frantsuzcha Dijon gorchitsasi — nozik donador tuzilma va yumshoq ta'm.",
    description_ru: 'Французская дижонская горчица — нежная зернистая текстура и мягкий вкус.',
    ingredients_uz: "Xantal urug'i, oq sharob sirkasi, suv, tuz, ziravorlar",
    ingredients_ru: 'Горчичные зёрна, винный уксус, вода, соль, специи',
    images: gallery('Dijon', 'F9A825'),
    price: 23000,
    oldPrice: 28000,
    discount: 18,
    weight: 200,
    unit: 'g',
    rating: 4.6,
    reviewCount: 58,
    isNew: true,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте.',
  },
  {
    id: 14,
    name_uz: "Asalli Gorchitsa",
    name_ru: 'Медовая горчица',
    slug: 'asalli-gorchitsa',
    category: 'mustard',
    description_uz: "Tabiiy asal qo'shilgan shirin-o'tkir gorchitsa. Tovuq va salatlar uchun.",
    description_ru: 'Сладко-острая горчица с натуральным мёдом. Для курицы и салатов.',
    ingredients_uz: "Xantal urug'i, asal, sirka, suv, tuz, ziravorlar",
    ingredients_ru: 'Горчичные зёрна, мёд, уксус, вода, соль, специи',
    images: gallery('Asal', 'FF6F00'),
    price: 25000,
    oldPrice: null,
    discount: null,
    weight: 200,
    unit: 'g',
    rating: 4.8,
    reviewCount: 84,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте.',
  },
  {
    id: 15,
    name_uz: "Abxaz Adjikasi",
    name_ru: 'Аджика Абхазская',
    slug: 'abxaz-adjikasi',
    category: 'adjika',
    description_uz: "An'anaviy o'tkir Abxaz adjikasi — qizil qalampir va ziravorlar aralashmasi.",
    description_ru: 'Традиционная острая абхазская аджика — смесь красного перца и специй.',
    ingredients_uz: "Qizil qalampir, sarimsoq, tuz, koriandr, ziravorlar",
    ingredients_ru: 'Красный перец, чеснок, соль, кориандр, специи',
    images: gallery('Adjika', 'C62828'),
    price: 17000,
    oldPrice: 22000,
    discount: 23,
    weight: 200,
    unit: 'g',
    rating: 4.7,
    reviewCount: 102,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
  {
    id: 16,
    name_uz: "Yashil Adjika",
    name_ru: 'Аджика Зелёная',
    slug: 'yashil-adjika',
    category: 'adjika',
    description_uz: "Yashil qalampir va ko'katlardan tayyorlangan mo''tadil achchiqlikdagi adjika.",
    description_ru: 'Аджика умеренной остроты из зелёного перца и зелени.',
    ingredients_uz: "Yashil qalampir, ko'katlar, sarimsoq, tuz, ziravorlar",
    ingredients_ru: 'Зелёный перец, зелень, чеснок, соль, специи',
    images: gallery('Yashil', '2E7D32'),
    price: 18000,
    oldPrice: null,
    discount: null,
    weight: 200,
    unit: 'g',
    rating: 4.5,
    reviewCount: 47,
    isNew: true,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
  {
    id: 17,
    name_uz: "Chimboy Klassik To'plam",
    name_ru: 'Набор Chimboy Классик',
    slug: 'chimboy-klassik-toplam',
    category: 'gift-sets',
    description_uz: "Mayonez, ketchup va gorchitsadan iborat sovg'abop to'plam. Bayramlar uchun ajoyib tanlov.",
    description_ru: 'Подарочный набор из майонеза, кетчупа и горчицы. Отличный выбор для праздников.',
    ingredients_uz: "Provansal mayonez, klassik ketchup, klassik gorchitsa",
    ingredients_ru: 'Майонез Провансаль, классический кетчуп, классическая горчица',
    images: gallery('Toplam', 'FF6F00'),
    price: 59000,
    oldPrice: 75000,
    discount: 21,
    weight: 1000,
    unit: 'g',
    rating: 4.9,
    reviewCount: 38,
    isNew: false,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Har bir mahsulotning saqlash shartlariga rioya qiling.",
    storageInfo_ru: 'Соблюдайте условия хранения каждого продукта.',
  },
  {
    id: 18,
    name_uz: "Premium Sous To'plami",
    name_ru: 'Премиум набор соусов',
    slug: 'premium-sous-toplami',
    category: 'gift-sets',
    description_uz: "5 xil premium sousdan iborat lyuks to'plam. Sovg'a uchun mukammal.",
    description_ru: 'Люкс-набор из 5 видов премиальных соусов. Идеален для подарка.',
    ingredients_uz: "BBQ, pishloqli, sezar, tartar va sarimsoqli souslar",
    ingredients_ru: 'Соусы BBQ, сырный, цезарь, тартар и чесночный',
    images: gallery('Premium Set', 'B71C1C'),
    price: 99000,
    oldPrice: null,
    discount: null,
    weight: 1000,
    unit: 'g',
    rating: 4.8,
    reviewCount: 29,
    isNew: true,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
  {
    id: 19,
    name_uz: "Oilaviy Mayonez 900g",
    name_ru: 'Майонез Семейный 900г',
    slug: 'oilaviy-mayonez-900',
    category: 'mayonnaises',
    description_uz: "Katta oilalar uchun iqtisodiy 900g qadoq. Provansal retsepti asosida.",
    description_ru: 'Экономичная упаковка 900г для больших семей. По рецепту Провансаль.',
    ingredients_uz: "O'simlik yog'i, suv, tuxum sarig'i, sirka, tuz, shakar, xantal",
    ingredients_ru: 'Растительное масло, вода, яичный желток, уксус, соль, сахар, горчица',
    images: gallery('Oilaviy', 'D32F2F'),
    price: 45000,
    oldPrice: 54000,
    discount: 17,
    weight: 900,
    unit: 'g',
    rating: 4.7,
    reviewCount: 110,
    isNew: false,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "0°C dan +14°C gacha haroratda saqlang.",
    storageInfo_ru: 'Хранить при температуре от 0°C до +14°C.',
  },
  {
    id: 20,
    name_uz: "Pomidorli Ketchup 1kg",
    name_ru: 'Кетчуп Томатный 1кг',
    slug: 'pomidorli-ketchup-1kg',
    category: 'ketchups',
    description_uz: "Katta qadoqdagi pomidorli ketchup. Restoran va katta oilalar uchun.",
    description_ru: 'Томатный кетчуп в большой упаковке. Для ресторанов и больших семей.',
    ingredients_uz: "Pomidor pastasi, suv, shakar, tuz, sirka, ziravorlar",
    ingredients_ru: 'Томатная паста, вода, сахар, соль, уксус, специи',
    images: gallery('Ketchup 1kg', 'C62828'),
    price: 38000,
    oldPrice: null,
    discount: null,
    weight: 1000,
    unit: 'g',
    rating: 4.6,
    reviewCount: 67,
    isNew: false,
    isFeatured: false,
    inStock: true,
    storageInfo_uz: "Salqin, quruq joyda saqlang.",
    storageInfo_ru: 'Хранить в прохладном, сухом месте.',
  },
  {
    id: 21,
    name_uz: "Burger Sousi",
    name_ru: 'Соус для бургеров',
    slug: 'burger-sousi',
    category: 'sauces',
    description_uz: "Burgerlar uchun maxsus sous — mayonez, ketchup va ziravorlar uyg'unligi.",
    description_ru: 'Особый соус для бургеров — сочетание майонеза, кетчупа и специй.',
    ingredients_uz: "Mayonez asosi, pomidor pastasi, tuzlangan bodring, ziravorlar",
    ingredients_ru: 'Майонезная основа, томатная паста, солёные огурцы, специи',
    images: gallery('Burger', 'E53935'),
    price: 24000,
    oldPrice: 29000,
    discount: 17,
    weight: 300,
    unit: 'g',
    rating: 4.7,
    reviewCount: 88,
    isNew: true,
    isFeatured: true,
    inStock: true,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
  {
    id: 22,
    name_uz: "O'tkir Adjika Premium",
    name_ru: 'Аджика Острая Премиум',
    slug: 'otkir-adjika-premium',
    category: 'adjika',
    description_uz: "Eng o'tkir premium adjika — haqiqiy achchiqlik shinavandalari uchun.",
    description_ru: 'Самая острая премиальная аджика — для настоящих ценителей остроты.',
    ingredients_uz: "Achchiq qizil qalampir, sarimsoq, tuz, ziravorlar, yong'oq",
    ingredients_ru: 'Острый красный перец, чеснок, соль, специи, орехи',
    images: gallery('Premium Adjika', 'B71C1C'),
    price: 26000,
    oldPrice: null,
    discount: null,
    weight: 200,
    unit: 'g',
    rating: 4.9,
    reviewCount: 54,
    isNew: false,
    isFeatured: false,
    inStock: false,
    storageInfo_uz: "Sovutgichda saqlang.",
    storageInfo_ru: 'Хранить в холодильнике.',
  },
];

// Promotions — expiresAt are future ISO dates relative to mid-2026
export const promotions = [
  {
    id: 1,
    title_uz: "Provansal Mayonez -20%",
    title_ru: 'Майонез Провансаль -20%',
    productId: 1,
    discountPercent: 20,
    expiresAt: '2026-06-10T23:59:59',
    bannerImage: banner('Mayonez -20%'),
    promoCode: 'CHIMBOY10',
    type: 'weekly',
  },
  {
    id: 2,
    title_uz: "Klassik Ketchup -25%",
    title_ru: 'Кетчуп Классический -25%',
    productId: 5,
    discountPercent: 25,
    expiresAt: '2026-06-08T23:59:59',
    bannerImage: banner('Ketchup -25%', 'C62828'),
    promoCode: 'SUMMER20',
    type: 'ending',
  },
  {
    id: 3,
    title_uz: "Abxaz Adjikasi -23%",
    title_ru: 'Аджика Абхазская -23%',
    productId: 15,
    discountPercent: 23,
    expiresAt: '2026-06-20T23:59:59',
    bannerImage: banner('Adjika -23%', 'B71C1C'),
    promoCode: 'CHIMBOY10',
    type: 'seasonal',
  },
  {
    id: 4,
    title_uz: "Klassik To'plam -21%",
    title_ru: 'Набор Классик -21%',
    productId: 17,
    discountPercent: 21,
    expiresAt: '2026-06-30T23:59:59',
    bannerImage: banner('Toplam -21%', 'FF6F00'),
    promoCode: 'SUMMER20',
    type: 'seasonal',
  },
  {
    id: 5,
    title_uz: "Shashlik Ketchup -19%",
    title_ru: 'Кетчуп для шашлыка -19%',
    productId: 7,
    discountPercent: 19,
    expiresAt: '2026-06-07T23:59:59',
    bannerImage: banner('Shashlik -19%', 'C62828'),
    promoCode: 'CHIMBOY10',
    type: 'ending',
  },
  {
    id: 6,
    title_uz: "Sarimsoqli Mayonez -18%",
    title_ru: 'Майонез с чесноком -18%',
    productId: 3,
    discountPercent: 18,
    expiresAt: '2026-06-25T23:59:59',
    bannerImage: banner('Sarimsoq -18%', 'D32F2F'),
    promoCode: 'SUMMER20',
    type: 'weekly',
  },
];

// Valid promo codes
export const promoCodes = {
  CHIMBOY10: 10,
  CHIMBOY15: 15,
  SUMMER20: 20,
};

export const stores = [
  {
    id: 1,
    name_uz: "Chimboy Chilonzor",
    name_ru: 'Chimboy Чиланзар',
    city_uz: 'Toshkent', city_ru: 'Ташкент',
    address_uz: "Chilonzor tumani, Bunyodkor ko'chasi 12",
    address_ru: 'Чиланзарский район, улица Бунёдкор 12',
    phone: '+998 71 200 10 01',
    workingHours: '09:00 - 21:00',
    lat: 41.2856, lng: 69.2034,
  },
  {
    id: 2,
    name_uz: "Chimboy Yunusobod",
    name_ru: 'Chimboy Юнусабад',
    city_uz: 'Toshkent', city_ru: 'Ташкент',
    address_uz: "Yunusobod tumani, Amir Temur ko'chasi 108",
    address_ru: 'Юнусабадский район, улица Амира Темура 108',
    phone: '+998 71 200 10 02',
    workingHours: '09:00 - 22:00',
    lat: 41.3640, lng: 69.2890,
  },
  {
    id: 3,
    name_uz: "Chimboy Samarqand",
    name_ru: 'Chimboy Самарканд',
    city_uz: 'Samarqand', city_ru: 'Самарканд',
    address_uz: "Registon ko'chasi 45",
    address_ru: 'улица Регистан 45',
    phone: '+998 66 233 20 01',
    workingHours: '09:00 - 20:00',
    lat: 39.6542, lng: 66.9597,
  },
  {
    id: 4,
    name_uz: "Chimboy Buxoro",
    name_ru: 'Chimboy Бухара',
    city_uz: 'Buxoro', city_ru: 'Бухара',
    address_uz: "Mustaqillik ko'chasi 23",
    address_ru: 'улица Мустакиллик 23',
    phone: '+998 65 223 30 01',
    workingHours: '09:00 - 20:00',
    lat: 39.7747, lng: 64.4286,
  },
  {
    id: 5,
    name_uz: "Chimboy Namangan",
    name_ru: 'Chimboy Наманган',
    city_uz: 'Namangan', city_ru: 'Наманган',
    address_uz: "Navoiy ko'chasi 67",
    address_ru: 'улица Навои 67',
    phone: '+998 69 234 40 01',
    workingHours: '08:00 - 20:00',
    lat: 40.9983, lng: 71.6726,
  },
  {
    id: 6,
    name_uz: "Chimboy Andijon",
    name_ru: 'Chimboy Андижан',
    city_uz: 'Andijon', city_ru: 'Андижан',
    address_uz: "Bobur shoh ko'chasi 89",
    address_ru: 'улица Бабур шах 89',
    phone: '+998 74 223 50 01',
    workingHours: '08:00 - 20:00',
    lat: 40.7821, lng: 72.3442,
  },
  {
    id: 7,
    name_uz: "Chimboy Farg'ona",
    name_ru: 'Chimboy Фергана',
    city_uz: "Farg'ona", city_ru: 'Фергана',
    address_uz: "Mustaqillik ko'chasi 34",
    address_ru: 'улица Мустакиллик 34',
    phone: '+998 73 244 60 01',
    workingHours: '09:00 - 20:00',
    lat: 40.3864, lng: 71.7864,
  },
  {
    id: 8,
    name_uz: "Chimboy Nukus",
    name_ru: 'Chimboy Нукус',
    city_uz: 'Nukus', city_ru: 'Нукус',
    address_uz: "Dosnazarov ko'chasi 12",
    address_ru: 'улица Досназарова 12',
    phone: '+998 61 222 70 01',
    workingHours: '09:00 - 19:00',
    lat: 42.4731, lng: 59.6103,
  },
  {
    id: 9,
    name_uz: "Chimboy Termiz",
    name_ru: 'Chimboy Термез',
    city_uz: 'Termiz', city_ru: 'Термез',
    address_uz: "Al-Termiziy ko'chasi 5",
    address_ru: 'улица Ал-Термизи 5',
    phone: '+998 76 227 80 01',
    workingHours: '09:00 - 19:00',
    lat: 37.2242, lng: 67.2783,
  },
];

export const reviews = [
  { id: 1, productId: 1, userName: 'Aziz Karimov', rating: 5, comment: "Ajoyib mayonez! Ta'mi juda yaxshi, oilamiz doim shuni oladi.", date: '2026-05-20' },
  { id: 2, productId: 1, userName: 'Malika Yusupova', rating: 4, comment: "Yaxshi mahsulot, lekin narxi biroz qimmat.", date: '2026-05-15' },
  { id: 3, productId: 1, userName: 'Дмитрий Ким', rating: 5, comment: 'Отличный майонез, всегда свежий. Рекомендую!', date: '2026-05-10' },
  { id: 4, productId: 5, userName: 'Jasur Toshmatov', rating: 5, comment: "Ketchupi haqiqiy pomidor ta'mi bor. Zo'r!", date: '2026-05-18' },
  { id: 5, productId: 5, userName: 'Nilufar Saidova', rating: 4, comment: "Bolalarim juda yaxshi ko'radi.", date: '2026-05-12' },
  { id: 6, productId: 3, userName: 'Bekzod Rahimov', rating: 5, comment: "Sarimsoqli mayonez kabob bilan ajoyib!", date: '2026-05-22' },
  { id: 7, productId: 15, userName: 'Olga Petrova', rating: 5, comment: 'Очень острая и вкусная аджика, как домашняя!', date: '2026-05-19' },
  { id: 8, productId: 7, userName: 'Sardor Aliyev', rating: 5, comment: "Shashlik uchun eng zo'r ketchup.", date: '2026-05-25' },
  { id: 9, productId: 11, userName: 'Kamola Ergasheva', rating: 4, comment: 'BBQ sous juda mazali, lekin biroz shirin.', date: '2026-05-08' },
  { id: 10, productId: 17, userName: 'Rustam Nazarov', rating: 5, comment: "Sovg'a uchun ajoyib to'plam, hammaga yoqdi!", date: '2026-05-28' },
];

export const stats = {
  yearsOfExperience: 20,
  products: 50,
  stores: 1000,
  customers: 5000000,
};

export const news = [
  {
    id: 1,
    title_uz: "Chimboy yangi premium souslar liniyasini taqdim etadi",
    title_ru: 'Chimboy представляет новую линейку премиальных соусов',
    excerpt_uz: "Brendimiz 5 xil yangi premium sousni bozorga chiqardi — pishloqli, sezar, tartar va boshqalar.",
    excerpt_ru: 'Наш бренд выпустил 5 новых премиальных соусов — сырный, цезарь, тартар и другие.',
    date: '2026-05-28',
    image: img('Yangilik 1', 'D32F2F'),
  },
  {
    id: 2,
    title_uz: "1000-chi Chimboy do'koni ochildi",
    title_ru: 'Открылся 1000-й магазин Chimboy',
    excerpt_uz: "Bugun Toshkentda bizning 1000-chi rasmiy do'konimiz tantanali ravishda ochildi.",
    excerpt_ru: 'Сегодня в Ташкенте торжественно открылся наш 1000-й официальный магазин.',
    date: '2026-05-20',
    image: img('Yangilik 2', 'C62828'),
  },
  {
    id: 3,
    title_uz: "Chimboy xalqaro ISO 22000 sertifikatini oldi",
    title_ru: 'Chimboy получил международный сертификат ISO 22000',
    excerpt_uz: "Mahsulotlarimiz sifati xalqaro ISO 22000 oziq-ovqat xavfsizligi standarti bilan tasdiqlandi.",
    excerpt_ru: 'Качество нашей продукции подтверждено международным стандартом ISO 22000.',
    date: '2026-05-12',
    image: img('Yangilik 3', 'B71C1C'),
  },
];

// Hero slides
export const heroSlides = [
  {
    id: 1,
    title_uz: "Tabiiy ta'm, oilaviy an'ana",
    title_ru: 'Натуральный вкус, семейная традиция',
    subtitle_uz: "20 yildan beri O'zbekiston dasturxonlarida",
    subtitle_ru: 'Уже 20 лет на столах Узбекистана',
    image: banner("Chimboy — Tabiiy ta'm", 'B71C1C'),
    cta_uz: 'Mahsulotlarni ko\'rish', cta_ru: 'Смотреть продукты',
    link: '/products',
  },
  {
    id: 2,
    title_uz: "Yangi premium souslar",
    title_ru: 'Новые премиальные соусы',
    subtitle_uz: "BBQ, pishloqli, sezar va boshqalar",
    subtitle_ru: 'BBQ, сырный, цезарь и другие',
    image: banner('Premium Souslar', 'D32F2F'),
    cta_uz: 'Hozir sotib olish', cta_ru: 'Купить сейчас',
    link: '/products?category=sauces',
  },
  {
    id: 3,
    title_uz: "Yozgi chegirmalar -25% gacha",
    title_ru: 'Летние скидки до -25%',
    subtitle_uz: "Sevimli mahsulotlaringizga maxsus narxlar",
    subtitle_ru: 'Специальные цены на любимые продукты',
    image: banner('Yozgi Chegirmalar', 'FF6F00'),
    cta_uz: 'Aksiyalarni ko\'rish', cta_ru: 'Смотреть акции',
    link: '/promotions',
  },
];

// Brand timeline milestones (About page)
export const milestones = [
  { year: 2006, title_uz: 'Tashkil etildi', title_ru: 'Основание', desc_uz: "Chimboy brendi Toshkentda kichik sex sifatida ish boshladi.", desc_ru: 'Бренд Chimboy начал работу как небольшой цех в Ташкенте.' },
  { year: 2011, title_uz: 'Kengayish', title_ru: 'Расширение', desc_uz: "Ishlab chiqarish quvvati 10 barobar oshdi.", desc_ru: 'Производственные мощности выросли в 10 раз.' },
  { year: 2016, title_uz: 'Yangi zavod', title_ru: 'Новый завод', desc_uz: "Zamonaviy avtomatlashtirilgan zavod ishga tushirildi.", desc_ru: 'Запущен современный автоматизированный завод.' },
  { year: 2021, title_uz: 'Eksport', title_ru: 'Экспорт', desc_uz: "Mahsulotlar qo'shni davlatlarga eksport qilina boshladi.", desc_ru: 'Продукция начала экспортироваться в соседние страны.' },
  { year: 2026, title_uz: '1000+ do\'kon', title_ru: '1000+ магазинов', desc_uz: "Butun O'zbekiston bo'ylab 1000 dan ortiq do'kon.", desc_ru: 'Более 1000 магазинов по всему Узбекистану.' },
];

export const team = [
  { id: 1, name: 'Aziz Yo\'ldoshev', role_uz: 'Bosh direktor', role_ru: 'Генеральный директor', avatar: img('AY', '212121') },
  { id: 2, name: 'Dilnoza Karimova', role_uz: 'Marketing rahbari', role_ru: 'Руководитель маркетинга', avatar: img('DK', '212121') },
  { id: 3, name: 'Sherzod Aliyev', role_uz: 'Ishlab chiqarish rahbari', role_ru: 'Руководитель производства', avatar: img('SA', '212121') },
  { id: 4, name: 'Madina Tosheva', role_uz: 'Sifat nazorati', role_ru: 'Контроль качества', avatar: img('MT', '212121') },
];

export const certificates = [
  { id: 1, title: 'ISO 22000', image: img('ISO 22000', '2E7D32') },
  { id: 2, title: 'GOST', image: img('GOST', '1565C0') },
  { id: 3, title: 'HALAL', image: img('HALAL', '2E7D32') },
  { id: 4, title: 'HACCP', image: img('HACCP', 'F57F17') },
];

// Mock orders for profile page
export const mockOrders = [
  { id: 'CH-2026-4821', date: '2026-05-28', items: 3, total: 89000, status: 'delivered' },
  { id: 'CH-2026-4790', date: '2026-05-20', items: 5, total: 142000, status: 'shipped' },
  { id: 'CH-2026-4755', date: '2026-05-12', items: 2, total: 47000, status: 'processing' },
  { id: 'CH-2026-4699', date: '2026-04-30', items: 4, total: 118000, status: 'delivered' },
  { id: 'CH-2026-4612', date: '2026-04-18', items: 1, total: 28000, status: 'cancelled' },
];

export const pointsHistory = [
  { id: 1, date: '2026-05-28', description_uz: 'Buyurtma CH-2026-4821', description_ru: 'Заказ CH-2026-4821', points: 89 },
  { id: 2, date: '2026-05-20', description_uz: 'Buyurtma CH-2026-4790', description_ru: 'Заказ CH-2026-4790', points: 142 },
  { id: 3, date: '2026-05-12', description_uz: 'Buyurtma CH-2026-4755', description_ru: 'Заказ CH-2026-4755', points: 47 },
];
